FROM arm32v7/debian:stretch

WORKDIR /botejao

RUN apt update && apt upgrade -y && apt install -y \
    build-essential \
    pkg-config \
    openssl \
    libssl-dev \
    curl \
    wget \
    git \
    firefox-esr \
    xvfb \
    vim \
    tmux


CMD /bin/bash

