FROM botejao_base:0.1

WORKDIR /botejao

RUN git fetch --all \
    && git reset --hard origin/master \
    && /bin/bash -c "source ~/.profile && cargo update && cargo build -vv"


CMD /bin/bash -c "export PATH=$PATH:$(pwd) && source ~/.profile && xvfb-run env RUST_BACKTRACE=1 cargo run -vv"

